**13.	Найдите спектральное разложение матрицы A с помощью python. Используйте функцию numpy.linalg.eigh, которая поможет рассчитать собственные числа и векторы матрицы.**

$A = V ∙ Λ ∙ V^{-1} $

In [1]:
import numpy as np
from numpy.ma.extras import hstack


def spectral_decomposition(matrix):

    #Найдем собственные значения и векторы матрицы
    eigenvalues, eigenvectors = np.linalg.eigh(matrix)
    
    print("Собственные значения:\n")
    for i, eigenvalue in enumerate(eigenvalues):
        print(f"λ{i+1} = {eigenvalue}\n")

    print("Собственные векторы:\n")
    for i, eigenvector in enumerate(eigenvectors.T):
        print(f"V{i+1} = {eigenvector}\n")
        
    #Собственные значения составляют диагональ матрицы лямбда
    lambda_matrix = np.diag(eigenvalues)
    
    #Собственные векторы составляют матрицу V и обратную V
    V_matrix = eigenvectors
    inv_V_matrix = np.linalg.inv(V_matrix)
    
    #Проверим, что произведение компонент разложения равно исходной матрице
    temp = np.dot(V_matrix, lambda_matrix)
    result = np.dot(temp, inv_V_matrix)
    
    print('Произведение компонент разложения: \n')
    print(result)

In [2]:
A = np.array([[1., 3., 4.],
              [3., 3., 1.],
              [4., 1., 2.]])

spectral_decomposition(A)

Собственные значения:

λ1 = -3.020699255079208

λ2 = 1.6652777053317827

λ3 = 7.355421549747427

Собственные векторы:

V1 = [ 0.77532334 -0.2934401  -0.55925542]

V2 = [ 0.1440438  -0.78000906  0.60896408]

V3 = [-0.61491877 -0.55270134 -0.562491  ]

Произведение компонент разложения: 

[[1. 3. 4.]
 [3. 3. 1.]
 [4. 1. 2.]]


In [3]:
import numpy as np

data_x = np.array([(5.8, 1.2), (5.6, 1.5), (6.5, 1.5), (6.1, 1.3), (6.4, 1.3), (7.7, 2.0), (6.0, 1.8), (5.6, 1.3), (6.0, 1.6), (5.8, 1.9), (5.7, 2.0), (6.3, 1.5), (6.2, 1.8), (7.7, 2.3), (5.8, 1.2), (6.3, 1.8), (6.0, 1.0), (6.2, 1.3), (5.7, 1.3), (6.3, 1.9), (6.7, 2.5), (5.5, 1.2), (4.9, 1.0), (6.1, 1.4), (6.0, 1.6), (7.2, 2.5), (7.3, 1.8), (6.6, 1.4), (5.6, 2.0), (5.5, 1.0), (6.4, 2.2), (5.6, 1.3), (6.6, 1.3), (6.9, 2.1), (6.8, 2.1), (5.7, 1.3), (7.0, 1.4), (6.1, 1.4), (6.1, 1.8), (6.7, 1.7), (6.0, 1.5), (6.5, 1.8), (6.4, 1.5), (6.9, 1.5), (5.6, 1.3), (6.7, 1.4), (5.8, 1.9), (6.3, 1.3), (6.7, 2.1), (6.2, 2.3), (6.3, 2.4), (6.7, 1.8), (6.4, 2.3), (6.2, 1.5), (6.1, 1.4), (7.1, 2.1), (5.7, 1.0), (6.8, 1.4), (6.8, 2.3), (5.1, 1.1), (4.9, 1.7), (5.9, 1.8), (7.4, 1.9), (6.5, 2.0), (6.7, 1.5), (6.5, 2.0), (5.8, 1.0), (6.4, 2.1), (7.6, 2.1), (5.8, 2.4), (7.7, 2.2), (6.3, 1.5), (5.0, 1.0), (6.3, 1.6), (7.7, 2.3), (6.4, 1.9), (6.5, 2.2), (5.7, 1.2), (6.9, 2.3), (5.7, 1.3), (6.1, 1.2), (5.4, 1.5), (5.2, 1.4), (6.7, 2.3), (7.9, 2.0), (5.6, 1.1), (7.2, 1.8), (5.5, 1.3), (7.2, 1.6), (6.3, 2.5), (6.3, 1.8), (6.7, 2.4), (5.0, 1.0), (6.4, 1.8), (6.9, 2.3), (5.5, 1.3), (5.5, 1.1), (5.9, 1.5), (6.0, 1.5), (5.9, 1.8)])
data_y = np.array([-1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, -1, 1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1])

# здесь продолжайте программу

In [1]:
import numpy as np

# добавим столбец единиц для свободного члена
X = np.hstack((np.ones((data_x.shape[0], 1)), data_x))
y = data_y.reshape(-1, 1)  # делаем столбец-вектор

w = np.linalg.inv(X.T@X) @ X.T @ y
#
# # считаем отступы (margins)
a = w.T @ X.T
margin = a * data_y
#
# # считаем Q = sum (1 - margin)^2
Q = np.sum((1 - margin) ** 2)
w
# -3.313071
# 0.006175
# 1.953703
X.T@(X@w - y)


NameError: name 'data_x' is not defined

In [128]:
import numpy as np

# исходная функция, которую нужно аппроксимировать моделью a(x)
def func(x):
    return 0.1 * x**2 - np.sin(x) + 5.


# здесь объявляйте необходимые функции

coord_x = np.arange(-5.0, 5.0, 0.1).reshape(-1,1) # значения по оси абсцисс [-5; 5] с шагом 0.1
coord_y = func(coord_x).reshape(-1,1) # значения функции по оси ординат

sz = len(coord_x)	# количество значений функций (точек)
eta = np.array([0.1, 0.01, 0.001, 0.0001]).reshape(-1,1) # шаг обучения для каждого параметра w0, w1, w2, w3
w = np.array([.0,.0, .0,.0]).reshape(-1,1) # начальные значения параметров модели
N = 200 # число итераций градиентного алгоритма
X = np.hstack((np.ones((coord_x.shape[0],1)),coord_x,coord_x**2,coord_x**3))
fx = coord_y
for _ in range(N):
    gradient = 2/sz * X.T @ (X@w - fx)
    w -= eta * gradient
Q = np.mean((X@w - fx)**2)



In [136]:
import numpy as np


# экспоненциальная функция потерь
def loss(w, x, y):
    M = np.dot(x, w) * y
    return np.exp(-M)


# производная экспоненциальной функции потерь по вектору w
def df(w, x, y):
    M = np.dot(x, w) * y
    return -np.exp(-M) * x.T * y


data_x = [(5.8, 1.2), (5.6, 1.5), (6.5, 1.5), (6.1, 1.3), (6.4, 1.3), (7.7, 2.0), (6.0, 1.8), (5.6, 1.3), (6.0, 1.6), (5.8, 1.9), (5.7, 2.0), (6.3, 1.5), (6.2, 1.8), (7.7, 2.3), (5.8, 1.2), (6.3, 1.8), (6.0, 1.0), (6.2, 1.3), (5.7, 1.3), (6.3, 1.9), (6.7, 2.5), (5.5, 1.2), (4.9, 1.0), (6.1, 1.4), (6.0, 1.6), (7.2, 2.5), (7.3, 1.8), (6.6, 1.4), (5.6, 2.0), (5.5, 1.0), (6.4, 2.2), (5.6, 1.3), (6.6, 1.3), (6.9, 2.1), (6.8, 2.1), (5.7, 1.3), (7.0, 1.4), (6.1, 1.4), (6.1, 1.8), (6.7, 1.7), (6.0, 1.5), (6.5, 1.8), (6.4, 1.5), (6.9, 1.5), (5.6, 1.3), (6.7, 1.4), (5.8, 1.9), (6.3, 1.3), (6.7, 2.1), (6.2, 2.3), (6.3, 2.4), (6.7, 1.8), (6.4, 2.3), (6.2, 1.5), (6.1, 1.4), (7.1, 2.1), (5.7, 1.0), (6.8, 1.4), (6.8, 2.3), (5.1, 1.1), (4.9, 1.7), (5.9, 1.8), (7.4, 1.9), (6.5, 2.0), (6.7, 1.5), (6.5, 2.0), (5.8, 1.0), (6.4, 2.1), (7.6, 2.1), (5.8, 2.4), (7.7, 2.2), (6.3, 1.5), (5.0, 1.0), (6.3, 1.6), (7.7, 2.3), (6.4, 1.9), (6.5, 2.2), (5.7, 1.2), (6.9, 2.3), (5.7, 1.3), (6.1, 1.2), (5.4, 1.5), (5.2, 1.4), (6.7, 2.3), (7.9, 2.0), (5.6, 1.1), (7.2, 1.8), (5.5, 1.3), (7.2, 1.6), (6.3, 2.5), (6.3, 1.8), (6.7, 2.4), (5.0, 1.0), (6.4, 1.8), (6.9, 2.3), (5.5, 1.3), (5.5, 1.1), (5.9, 1.5), (6.0, 1.5), (5.9, 1.8)]
data_y = [-1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, -1, 1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1]

x_train = np.array([[1, x[0], x[1]] for x in data_x])
y_train = np.array(data_y)

n_train = len(x_train)  # размер обучающей выборки
w = np.array([0.0, 0.0, 0.0])  # начальные весовые коэффициенты
nt = np.array([0.5, 0.01, 0.01])  # шаг обучения для каждого параметра w0, w1, w2
lm = 0.01  # значение параметра лямбда для вычисления скользящего экспоненциального среднего
N = 500  # число итераций алгоритма SGD
batch_size = 10 # размер мини-батча (величина K = 10)
margin_init = np.dot(w,x_train.T) * y_train
Qe = np.mean(margin_init)# начальное значение среднего эмпирического риска
np.random.seed(0) # генерация одинаковых последовательностей псевдослучайных чисел
for _ in range(N):
    k = np.random.randint(0, n_train-batch_size-1)
    Qk = np.mean(loss(w, x_train[k : k+batch_size], y_train[k : k+batch_size]))
    Qe = lm * Qk + (1-lm) * Qe
    w = w - nt * np.mean(df(w, x_train[k : k+batch_size], y_train[k : k+batch_size]),axis=1)

Q = np.mean(np.dot(x_train,w)*y_train<0)


np.float64(0.07)

In [131]:
import numpy as np


# экспоненциальная функция потерь
def loss(w, x, y):
    M = np.dot(x, w) * y
    return np.exp(-M)


# производная экспоненциальной функции потерь по вектору w
def df(w, x, y):
    M = np.dot(x, w) * y
    return -np.exp(-M) * x.T * y


data_x = [(5.8, 1.2), (5.6, 1.5), (6.5, 1.5), (6.1, 1.3), (6.4, 1.3), (7.7, 2.0), (6.0, 1.8), (5.6, 1.3), (6.0, 1.6), (5.8, 1.9), (5.7, 2.0), (6.3, 1.5), (6.2, 1.8), (7.7, 2.3), (5.8, 1.2), (6.3, 1.8), (6.0, 1.0), (6.2, 1.3), (5.7, 1.3), (6.3, 1.9), (6.7, 2.5), (5.5, 1.2), (4.9, 1.0), (6.1, 1.4), (6.0, 1.6), (7.2, 2.5), (7.3, 1.8), (6.6, 1.4), (5.6, 2.0), (5.5, 1.0), (6.4, 2.2), (5.6, 1.3), (6.6, 1.3), (6.9, 2.1), (6.8, 2.1), (5.7, 1.3), (7.0, 1.4), (6.1, 1.4), (6.1, 1.8), (6.7, 1.7), (6.0, 1.5), (6.5, 1.8), (6.4, 1.5), (6.9, 1.5), (5.6, 1.3), (6.7, 1.4), (5.8, 1.9), (6.3, 1.3), (6.7, 2.1), (6.2, 2.3), (6.3, 2.4), (6.7, 1.8), (6.4, 2.3), (6.2, 1.5), (6.1, 1.4), (7.1, 2.1), (5.7, 1.0), (6.8, 1.4), (6.8, 2.3), (5.1, 1.1), (4.9, 1.7), (5.9, 1.8), (7.4, 1.9), (6.5, 2.0), (6.7, 1.5), (6.5, 2.0), (5.8, 1.0), (6.4, 2.1), (7.6, 2.1), (5.8, 2.4), (7.7, 2.2), (6.3, 1.5), (5.0, 1.0), (6.3, 1.6), (7.7, 2.3), (6.4, 1.9), (6.5, 2.2), (5.7, 1.2), (6.9, 2.3), (5.7, 1.3), (6.1, 1.2), (5.4, 1.5), (5.2, 1.4), (6.7, 2.3), (7.9, 2.0), (5.6, 1.1), (7.2, 1.8), (5.5, 1.3), (7.2, 1.6), (6.3, 2.5), (6.3, 1.8), (6.7, 2.4), (5.0, 1.0), (6.4, 1.8), (6.9, 2.3), (5.5, 1.3), (5.5, 1.1), (5.9, 1.5), (6.0, 1.5), (5.9, 1.8)]
data_y = [-1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, -1, 1, -1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1]

x_train = np.array([[1, x[0], x[1]] for x in data_x])
y_train = np.array(data_y)

n_train = len(x_train)  # размер обучающей выборки
w = [0.0, 0.0, 0.0]  # начальные весовые коэффициенты
nt = np.array([0.5, 0.01, 0.01])  # шаг обучения для каждого параметра w0, w1, w2
lm = 0.01  # значение параметра лямбда для вычисления скользящего экспоненциального среднего
N = 500  # число итераций алгоритма SGD
batch_size = 10 # размер мини-батча (величина K = 10)

Qe = (np.dot(x_train,w)*y_train<0).mean()
np.random.seed(0)
# здесь продолжайте программу
for _ in range(N):
  k = np.random.randint(0, n_train-batch_size-1)
  Qk = loss(w, x_train[k : k+batch_size], y_train[k : k+batch_size])
  Qe = lm * loss(w, x_train[k : k+batch_size], y_train[k : k+batch_size]).mean() + (1-lm)*Qe
  w = w - nt * df(w, x_train[k : k+batch_size], y_train[k : k+batch_size]).mean(axis=1)
Q = (np.dot(x_train,w)*y_train<0).mean()
Qe

np.float64(0.7027033228102064)

In [18]:
import numpy as np
a = np.arange(4).reshape(-1,1)
b = np.array([0.1,0.01,0.001,0.001])
print(b.T*a)

[[0.    0.    0.    0.   ]
 [0.1   0.01  0.001 0.001]
 [0.2   0.02  0.002 0.002]
 [0.3   0.03  0.003 0.003]]
