In [ ]:
import numpy as np

np.random.seed(0) # псевдослучайные числа образуют одну и ту же последовательность (при каждом запуске)
x = np.arange(-1.0, 1.0, 0.1) # аргумент [-1; 1] с шагом 0,1


model_a = lambda xx, ww: (ww[0] + ww[1] * xx) # модель
Y = -5.2 + 0.7 * x + np.random.normal(0, 0.1, len(x)) # вектор целевых значений


# здесь продолжайте программу

In [34]:
ones_col = np.ones(x.shape[0])
X = np.vstack((np.ones(20),x)).T
X.shape


(20, 2)

In [36]:
np.linalg.inv(X.T @ X) @ X.T @ Y

array([-5.14605924,  0.64014601])

In [8]:
import numpy as np
import math

N = 1_000_000
R = 1/4

x = np.random.rand(N)
y = np.random.rand(N)

inside = ((x - 0.5)**2 + (y-0.5)**2) <= R**2


pi = np.mean(inside) * 16

print(pi)

3.142416


In [5]:
import numpy as np
from sklearn.cluster import DBSCAN

X = [(58, 138), (74, 96), (103, 82), (135, 76), (162, 79), (184, 97), (206, 111), (231, 118), (251, 118),  (275, 110), (298, 86), (320, 68), (344, 62), (376, 61), (403, 75), (414, 90), (430, 100), (254, 80), (219, 85), (288, 66), (260, 92), (201, 76), (162, 66), (127, 135), (97, 143), (83, 160), (82, 177), (88, 199), (105, 205), (135, 208), (151, 198), (157, 169), (153, 152), (117, 158), (106, 168), (106, 185), (123, 188), (125, 171), (139, 163), (139, 183), (358, 127), (328, 132), (313, 146), (300, 169), (300, 181), (308, 197), (326, 206), (339, 209), (370, 199), (380, 184), (380, 147), (343, 154), (329, 169), (332, 184), (345, 185), (363, 159), (361, 177), (344, 169), (311, 175), (351, 89), (134, 96)]
X = np.array(X)

# здесь продолжайте программу
clustering = DBSCAN(eps=10, min_samples=10, metric='euclidean')
res = clustering.fit_predict(X)
res

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [14]:
import numpy as np
from sklearn.cluster import DBSCAN

X = [(58, 138), (74, 96), (103, 82), (135, 76), (162, 79), (184, 97), (206, 111), (231, 118), (251, 118),  (275, 110), (298, 86), (320, 68), (344, 62), (376, 61), (403, 75), (414, 90), (430, 100), (254, 80), (219, 85), (288, 66), (260, 92), (201, 76), (162, 66), (127, 135), (97, 143), (83, 160), (82, 177), (88, 199), (105, 205), (135, 208), (151, 198), (157, 169), (153, 152), (117, 158), (106, 168), (106, 185), (123, 188), (125, 171), (139, 163), (139, 183), (358, 127), (328, 132), (313, 146), (300, 169), (300, 181), (308, 197), (326, 206), (339, 209), (370, 199), (380, 184), (380, 147), (343, 154), (329, 169), (332, 184), (345, 185), (363, 159), (361, 177), (344, 169), (311, 175), (351, 89), (134, 96)]
X = np.array(X)

# здесь продолжайте программу
clustering = DBSCAN(eps=20, min_samples=3, metric='euclidean')
res = clustering.fit_predict(X)
res

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0,  0,  0,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1, -1, -1,  2,  2,  2, -1, -1, -1, -1, -1,
        2,  2,  2,  2,  2,  2,  2,  2, -1, -1])

In [18]:
eps = [i for i in range(10, 100, 5)]
min_samples = [i for i in range(1, 10)]
klstrs = []
n = []
params = []

for m_s in min_samples:
    for ep in eps:

        clustering = DBSCAN(eps=ep, min_samples=m_s, metric='euclidean')
        res = clustering.fit_predict(X)
        n.append(min(res))
        klstrs.append(np.unique(res).shape[0])
        params.append((m_s, ep))

for i, j in zip(klstrs, n):
    if i == 3 and j > -1:
        best_param = params[klstrs.index(i)]

ep = best_param[1]
m_s = best_param[0]
clustering = DBSCAN(eps=ep, min_samples=m_s, metric='euclidean')
res = clustering.fit_predict(X)
res.reshape(-1, 1).shape


(61, 1)

In [ ]:
import numpy as np

# исходная функция, которую нужно аппроксимировать моделью a(x)
def func(x):
    return 0.5 * x**2 - 0.1 * 1/np.exp(-x) + 0.5 * np.cos(2*x) - 2.


# здесь объявляйте необходимые функции


coord_x = np.arange(-5.0, 5.0, 0.1).reshape(-1,1) # значения по оси абсцисс [-5; 5] с шагом 0.1
coord_y = func(coord_x) # значения функции по оси ординат
coord_y = np.array(coord_y).reshape(-1,1)
sz = len(coord_x)	# количество значений функций (точек)
eta = np.array([0.01, 0.001, 0.0001, 0.01, 0.01]).reshape(-1,1) # шаг обучения для каждого параметра w0, w1, w2, w3, w4
w = np.array([0., 0., 0., 0., 0.]).reshape(-1,1) # начальные значения параметров модели
N = 500 # число итераций алгоритма SGD
lm = 0.02 # значение параметра лямбда для вычисления скользящего экспоненциального среднего
Y = np.array(coord_y).reshape(-1,1)
X = np.hstack([
    np.ones_like(coord_x),
    coord_x,
    coord_x**2,
    np.cos(2*coord_x),
    np.sin(2*coord_x)  
])
np.random.seed(0) # генерация одинаковых последовательностей псевдослучайных чисел

# начальная среднеквадратичная ошибка
Qe = np.mean((X @ w - coord_y)**2)

# стохастический градиентный спуск
for _ in range(N):
    k = np.random.randint(0, sz-1)
    x_k = X[k].reshape(-1,1)   
    y_k = coord_y.reshape(-1,1) 
    print(x_k.shape, y_k.shape)      

    # градиент для одного наблюдения
    gradient_k = 2 * (x_k @ w - y_k) @ x_k  # (5, 1)

    # обновление весов (поэлементно с разными eta)
    w -= eta * gradient_k

    # обновление ошибки Qe
    loss_k = ((x_k @ w - y_k)**2).item() # скаляр
    Qe = lm * loss_k + (1 - lm) * Qe

Q = np.mean((X @ w - coord_y)**2)

(5, 1) (100, 1)


ValueError: operands could not be broadcast together with shapes (5,1) (100,5) 